field: 7e98ec3a-8e3d-4d66-a22b-335820e54f2f # Innholdsblokker
fieldLayouts:
  6a0bb748-e9e1-4c3b-8706-4f803b838f0c:
    tabs:
      -
        elements:
          -
            fieldUid: ebbc7b86-4a69-44bd-b81d-a1e10ea6c419 # Kode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ebbc7b86-4a69-44bd-b81d-a1e10ea6c419: # Kode
    columnSuffix: daqehlun
    contentColumnType: mediumtext
    fieldGroup: null
    handle: code
    instructions: ''
    name: Kode
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: mediumtext
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: html
name: HTML
sortOrder: 6
