field: 7e98ec3a-8e3d-4d66-a22b-335820e54f2f # Innholdsblokker
fieldLayouts:
  00bad549-437e-45e3-b946-9f2d0bd2d5d5:
    tabs:
      -
        elements:
          -
            fieldUid: f3aa9675-93a2-42a3-ade9-ef0269d08b19 # Bilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b6ea25f-a4f9-4465-967d-63fee0d56689 # Bildetekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1b6ea25f-a4f9-4465-967d-63fee0d56689: # Bildetekst
    columnSuffix: emlbncsh
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Bildetekst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f3aa9675-93a2-42a3-ade9-ef0269d08b19: # Bilder
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Bilder
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:cdae5da6-eb49-4503-a8e3-3f29862a608c' # Media
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:cdae5da6-eb49-4503-a8e3-3f29862a608c' # Media
      singleUploadLocationSubpath: 'Lekeplass/{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image_two
name: 'Bilde (dobbel)'
sortOrder: 4
