field: 7e98ec3a-8e3d-4d66-a22b-335820e54f2f # Innholdsblokker
fieldLayouts:
  2fd0126d-d982-4cbd-a24e-15cba919f2ac:
    tabs:
      -
        elements:
          -
            fieldUid: 172c6eb1-bade-4a7a-9d39-26378b244a47 # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d951d953-3864-4994-80ae-2fb4a75a820d # Navn
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 64e77909-2b53-4677-91d9-b45655a4b73d # Tittel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5af285df-518d-41b1-b574-d1be489993cf # Klokkeslett
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5af285df-518d-41b1-b574-d1be489993cf: # Klokkeslett
    columnSuffix: ihujkeez
    contentColumnType: time
    fieldGroup: null
    handle: route_time
    instructions: ''
    name: Klokkeslett
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 30
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Time
  64e77909-2b53-4677-91d9-b45655a4b73d: # Tittel
    columnSuffix: kuoirplw
    contentColumnType: text
    fieldGroup: null
    handle: route_title
    instructions: ''
    name: Tittel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  172c6eb1-bade-4a7a-9d39-26378b244a47: # Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: route_media
    instructions: ''
    name: Media
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:cdae5da6-eb49-4503-a8e3-3f29862a608c' # Media
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:cdae5da6-eb49-4503-a8e3-3f29862a608c' # Media
      singleUploadLocationSubpath: 'Lekeplass/{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d951d953-3864-4994-80ae-2fb4a75a820d: # Navn
    columnSuffix: jaawcjnl
    contentColumnType: text
    fieldGroup: null
    handle: route_name
    instructions: ''
    name: Navn
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: route_stage
name: Etappe
sortOrder: 10
