fieldLayouts:
  0a35416a-89c8-4a7e-a2a4-9d319b7da01e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f23fb6e2-37bb-494d-a6ed-201392eee988 # Oppsummering
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cecc58c9-98f9-4509-b2f0-6cd51db5cb7e # Hovedbilde
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2b9885e7-4026-45e0-9b91-ab23db9ceac7 # Lenker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b073d6fe-271b-475a-8d3a-2501ad4ab7ed # Blokker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c99e203e-9aa3-47ec-ba1c-e189dc6aa9be
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Innhold
        sortOrder: 1
handle: inspo
hasTitleField: true
name: Inspirasjon
section: b1fcf98b-3e68-44ae-abbd-8e6ddaeca117 # Inspirasjon
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
