fieldLayouts:
  0abf74c7-c270-4124-ab49-5c39648e5c93:
    tabs:
      -
        elements:
          -
            fieldUid: e87bca4b-bd9f-4e75-ad15-c710228e9e8d # Deletittel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: cb31edef-84c1-4c85-b289-2fb84e6646ec # Delebilde
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: c45860de-5f1d-4d0f-b731-5c1528cd418f # Deletekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 637cb46c-92e4-4f26-b6c8-b493054c8408 # Ingress
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e98ec3a-8e3d-4d66-a22b-335820e54f2f # Innholdsblokker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Innhold
        sortOrder: 1
handle: playground
hasTitleField: true
name: Lekeplass
section: c0a032da-da26-4737-86a9-4e72d01060d7 # Lekeplass
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
