field: b073d6fe-271b-475a-8d3a-2501ad4ab7ed # Blokker
fieldLayouts:
  25eed14d-24d9-4711-93f9-86e79a976fb5:
    tabs:
      -
        elements:
          -
            fieldUid: d9356b4f-e996-4e7d-9bc5-ed6374f4c580 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d9356b4f-e996-4e7d-9bc5-ed6374f4c580: # Tekst
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: redactor
    instructions: 'Mellomtittel = h3.'
    name: Tekst
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Tekst
sortOrder: 1
