columnSuffix: ifagoubb
contentColumnType: string(620)
fieldGroup: e6d5362a-65e2-4487-9c94-4c3b8c8e48bf # Lekeplass-felter
handle: share_text
instructions: ''
name: Deletekst
searchable: false
settings:
  byteLimit: null
  charLimit: 155
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Om feltet ikke er utfylt brukes artikkelens ingress.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
