dateModified: 1660040825
email:
  fromEmail: jarand.ullestad@nationen.no
  fromName: Lab
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2b9885e7-4026-45e0-9b91-ab23db9ceac7: Lenker # Lenker
    04e8fcb2-3195-4e04-9008-e4a636779e66: Loop # Loop
    7c52f0e9-6e2e-4187-b07c-a85987a0ae8a: Sidebeskrivelse # Sidebeskrivelse
    9f8e4d0a-efa9-4326-aa97-e12ea9f90322: Lenke # Lenke
    12c43602-5522-4612-8789-89627a2bcb0f: Meny # Meny
    29ea60c5-d06b-4b6c-9eec-260ecc54721f: Meny # Meny
    34ba5c58-1f33-4d1d-8df8-73cca7ff1c66: Lenketekst # Lenketekst
    57a01c16-6c6f-4438-83c4-50bea3c1e1be: Kodesnutter # Kodesnutter
    60e9152a-ba6b-452c-bcc6-428892207bfa: 'Tips og triks' # Tips og triks
    128afd8b-a1fe-4bc8-a913-2b3c4ecc45f3: Tekst # Tekst
    459d3b34-d55f-4c02-bf87-b63eabc70ffd: Lenkeadresse # Lenkeadresse
    0469b546-ffca-4bf3-a3b4-3b4386239862: Kode # Kode
    826d49de-b5df-468f-b144-ffdb8cbfd516: Kode # Kode
    915c2d57-d23f-4e55-ab1f-1398020167fc: Kodesnutter # Kodesnutter
    2805e4bb-e9a3-40fa-825b-099323c42286: Entry # Entry
    3490f199-b868-44ac-b799-f151a928a42d: 'Tips og triks' # Tips og triks
    08715e09-2b04-4737-8933-c71821979f91: SVG # SVG
    699073cc-78ba-42c6-87f4-77b9873a662d: 'Public Schema' # Public Schema
    a1e2c619-c7bb-4e93-a8ad-706d14b6a2ea: Meny-felter # Meny-felter
    a9196df9-350e-4141-9724-eabb9295bb67: Lenke # Lenke
    a94191bb-057f-466a-823c-c121390522ed: Alt-tekst # Alt-tekst
    ab44a115-1c86-422c-aa37-88117c577abc: Lab # Lab
    b073d6fe-271b-475a-8d3a-2501ad4ab7ed: Blokker # Blokker
    b09e2feb-98df-440f-8a53-ad2938ecfbe9: Globaler-felter # Globaler-felter
    b1fcf98b-3e68-44ae-abbd-8e6ddaeca117: Inspirasjon # Inspirasjon
    bade9013-b550-4c8e-b854-090d585d62ad: Felles # Felles
    bb758d4c-742d-47fd-ad1a-174fa0b98f98: Media # Media
    c3af0b27-ff25-4c64-a9cb-f6aad24d5550: Media # Media
    cdae5da6-eb49-4503-a8e3-3f29862a608c: Media # Media
    cecc58c9-98f9-4509-b2f0-6cd51db5cb7e: Hovedbilde # Hovedbilde
    d15b34a0-586b-4378-81a4-d177b2c4f79b: Lab # Lab
    d9356b4f-e996-4e7d-9bc5-ed6374f4c580: Tekst # Tekst
    f23fb6e2-37bb-494d-a6ed-201392eee988: Oppsummering # Oppsummering
    f60ab164-fd6b-4527-8b32-09d4ccf420ce: Inspirasjon # Inspirasjon
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: 'Nationens digitale lekegrind.'
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - noindex
        - ''
        - ''
        - ''
        - ''
        - noimageindex
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage:
        - '45'
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: pro
  live: true
  name: Lab
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: Europe/Oslo
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
