columnSuffix: rnpggkhp
contentColumnType: string(600)
fieldGroup: bade9013-b550-4c8e-b854-090d585d62ad # Felles
handle: alt
instructions: ''
name: Alt-tekst
searchable: false
settings:
  byteLimit: null
  charLimit: 150
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
