columnSuffix: null
contentColumnType: string
fieldGroup: bade9013-b550-4c8e-b854-090d585d62ad # Felles
handle: links
instructions: ''
name: Lenker
searchable: false
settings:
  contentTable: '{{%matrixcontent_links}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
