defaultPlacement: end
enableVersioning: true
handle: inspo
name: Inspirasjon
propagationMethod: all
siteSettings:
  ab44a115-1c86-422c-aa37-88117c577abc: # lab
    enabledByDefault: true
    hasUrls: true
    template: inspirasjon/_entry
    uriFormat: 'inspirasjon/{slug}'
type: channel
