defaultPlacement: end
enableVersioning: true
handle: lekeplass
name: Lekeplass
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primær artikkel-side'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ab44a115-1c86-422c-aa37-88117c577abc: # Lab
    enabledByDefault: true
    hasUrls: true
    template: lekeplass/_article
    uriFormat: 'lekeplass/{slug}'
type: channel
