defaultPlacement: end
enableVersioning: true
handle: snippets
name: Kodesnutter
propagationMethod: all
siteSettings:
  ab44a115-1c86-422c-aa37-88117c577abc: # lab
    enabledByDefault: true
    hasUrls: true
    template: kodesnutter/_entry
    uriFormat: 'kodesnutter/{slug}'
type: channel
