defaultPlacement: end
enableVersioning: true
handle: tricks
name: 'Tips og triks'
previewTargets:
  -
    __assoc__:
      -
        - label
        - default
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ab44a115-1c86-422c-aa37-88117c577abc: # Lab
    enabledByDefault: true
    hasUrls: true
    template: _includes/_entry
    uriFormat: 'tips-og-triks/{slug}'
type: channel
